import { writable } from 'svelte/store';
import type { Project } from './types';

export const projects: Record<string, Project> = {
  goodwine: {
    title: "Goodwine",
    description: "Goodwine is a full-stack e-commerce experience for Mongolia's premium wine market. We built a polished mobile shopping app with category browsing, intelligent search, persistent cart, secure checkout, and real-time order tracking — all wrapped in a brand-forward UI that makes premium wine feel approachable.",
    description2: "Under the hood: secure phone-based authentication with token refresh, Qpay integration for one-tap payments, location-aware delivery with maps, and a custom favorites and order-history system. The app talks to a typed REST API and ships to both iOS and Android from a single codebase.",
    image: "/projects/goodwine.png",
    cover: "/projects/goodwine-cover.png",
    tags: ["Mobile E-commerce", "React Native", "Qpay"],
    projectImage1: "/projects/goodwine-2.png",
    projectDuration: "3 months",
    servicesProvided: "Mobile App Development",
  },
  amuse: {
    title: "Amuse-Bouche",
    description: "Amuse-Bouche is a QR-driven check-in and loyalty platform for restaurant and café groups across the Middle East. Members earn rewards by scanning a QR code at the venue, track multi-brand memberships, and watch their balance grow in both fiat and Bitcoin — a single app that turns every visit into a relationship.",
    description2: "We designed the entire mobile experience from the ground up: profile completion mechanics that drive 1.2x reward bonuses, multi-brand membership cards with check-in counters, a unified discover feed, and a frictionless QR check-in flow that pops a celebratory success state on scan. Built in React Native for iOS and Android.",
    image: "/projects/amuse.png",
    cover: "/projects/amuse-cover.png",
    tags: ["Loyalty", "QR Check-in", "React Native"],
    projectImage1: "/projects/amuse-2.png",
    projectDuration: "3 months",
    servicesProvided: "Mobile App Development",
  },
  wine: {
    title: "GoodWine Web",
    description: "The web counterpart to Goodwine — a complete Next.js commerce platform with a public storefront, customer accounts, and a full operational admin dashboard. Built on the T3 stack (Next.js, tRPC, Prisma, NextAuth) with type-safe APIs end-to-end, OpenAPI spec generation, and a typed Postgres schema designed for multi-category catalog management.",
    description2: "Features include a brand-forward storefront with category navigation and live inventory, role-based admin access, order lifecycle management, stock tracking with alerts, and a CMS-style product editor. Designed to be the operational backbone behind the Goodwine mobile app — one source of truth, two distribution channels.",
    image: "/projects/wine.png",
    cover: "/projects/goodwine-cover.png",
    tags: ["Web E-commerce", "Next.js", "tRPC"],
    projectImage1: "/projects/wine-2.jpg",
    projectDuration: "3 months",
    servicesProvided: "Web Platform & Admin",
  },
  nair: {
    title: "Nair",
    description: "Nair is Mongolia's first end-to-end celebration platform — covering weddings, ceremonies, traditional gatherings, and corporate events. We built the entire booking experience from venue discovery to vendor coordination, with multi-language support (Mongolian, English) and a curated catalog of trusted service providers across the country.",
    description2: "Beyond the booking flow, Nair includes a vendor onboarding pipeline, real-time availability calendars, transparent pricing tiers, and an editorial-style discovery feed that helps couples and families plan once-in-a-lifetime moments. Built on SvelteKit with Paraglide i18n and deployed on Vercel.",
    image: "/projects/nair.jpg",
    cover: "/projects/nair-cover.png",
    tags: ["Marketplace", "SvelteKit", "Multi-language"],
    projectImage1: "/projects/nair-2.jpg",
    projectDuration: "5 months",
    servicesProvided: "Full-stack Platform",
  },
  cmm: {
    title: "CMM MarketIQ",
    description: "MarketIQ is a Bloomberg-style B2B intelligence platform for capital markets professionals — delivering institutional-grade insights, deal flow tracking, live market feeds, and curated research to investors, analysts, and dealmakers across Mongolia and the wider region.",
    description2: "The platform combines a long-form editorial CMS, a structured entity database (companies, deals, sectors), a live MSE Top 20 ticker with sector breakdowns, and a personalized email digest engine. We led the IA, brand-system definition, design tokens, and Next.js implementation — and continue to run weekly insight publishing on the live site.",
    image: "/projects/cmm.png",
    cover: "/projects/cmm-cover.png",
    tags: ["B2B Platform", "Editorial CMS", "Next.js"],
    projectImage1: "/projects/cmm-2.jpg",
    projectDuration: "9 weeks",
    servicesProvided: "Brand & Platform Build",
  },
  juraan: {
    title: "Juraan",
    description: "A refined digital gallery for Juraan, a Mongolian bronze sculptor whose work explores mythology, spirituality, and the human condition. We built a museum-quality portfolio site that lets the bronze speak — every design decision serves the artwork, not the chrome around it.",
    description2: "Built on SvelteKit with a dark gallery aesthetic, high-resolution image optimization, an elegant lightbox system for individual sculpture detail pages, and integrated exhibition footage from his 2024 solo show. We also produced and color-graded the underlying photo and video archive — hundreds of frames sequenced across the live catalog of 40+ bronze works.",
    image: "/projects/juraan.jpg",
    cover: "/projects/juraan-cover.png",
    tags: ["Portfolio", "SvelteKit", "Gallery"],
    projectImage1: "/projects/juraan-2.jpg",
    projectDuration: "2 months",
    servicesProvided: "Web Build & Creative Direction",
  },
  mintpark: {
    title: "Mint Park",
    description: "MintPark is a cutting-edge NFT marketplace built on Bitcoin's Layer 2, designed to offer fast, low-cost transactions and seamless minting of digital assets. It provides a no-code tool for artists, enabling creators to easily mint and manage their NFTs without technical expertise.",
    description2: "As a Bitcoin Ordinals-enabled marketplace, MintPark supports innovative features like wrapped NFTs and aims to connect all Bitcoin Layer 2 solutions, removing liquidity fragmentation and creating a unified ecosystem for creators and collectors. MintPark bridges the gap between Bitcoin's security and the growing demand for scalable, efficient NFT solutions.",
    image: "/Mintpark.png",
    tags: ["Cross-Chain Marketplace", "CaaS", "Creator Program"],
    projectImage1: "/mintpark2.png",
    projectDuration: "4 months",
    servicesProvided: "dApp Development",
  },
};

export const currentProject = writable<Project | null>(null);
